### PR TITLE
[typescript] test and fix subscriptions

### LINKED ISSUE #65: 4.0.1 typescript error TS2322 on subscriptions
### Are you submitting a **bug report** or a **feature request**?
Bug

### What is the current behavior?
I introduced changes in #61 that produce typescript errors.

### What is the expected behavior?
One example:

```
error TS2322: Type '{ subscription: { errors: true; values: true; }; children: (form: FormSpyRenderProps) => Element; }' is not assignable to type 'IntrinsicAttributes & FormSpyProps & { children?: ReactNode; }'.
  Type '{ subscription: { errors: true; values: true; }; children: (form: FormSpyRenderProps) => Element; }' is not assignable to type 'FormSpyProps'.
    Types of property 'subscription' are incompatible.
      Type '{ errors: true; values: true; }' is not assignable to type 'FormSubscription'.
        Property 'active' is missing in type '{ errors: true; values: true; }'.
```

### What's your environment?
 final-form        ^4.0.1 
 react-final-form  ^3.0.2 

### Other information
I created the problem, I'll PR the fix ASAP.  Working on it now.

### PR DESCRIPTION
**Pull request by rosskevin**
Closes #65 

Please release ASAP for broken TS subscriptions I introduced in #61

### CODE REVIEW

**Comment by erikras** [comment]
Codacy is a little dumb about typescript. I wonder if its expectations can be modified...

**Comment by rosskevin** [comment]
@erikras - thank you

@brikou - not sure if I am going back to something that errored in your original PR, but the tests added here (and in react-final-form) seem to confirm this is valid. If you find a problem, please add a test case (here or in the react project) if you find more issues and I'll be happy to help solve them.

**Comment by rosskevin** [comment]
@erikras final-for 4.0.2 does not include these changes.  I've re-installed the package but you can see in `indext.d.ts` that `Subscription` still exists.

**Comment by erikras** [comment]
That's bizarre. Let's try this again....

**Comment by erikras** [comment]
[Better in `v4.0.3`](https://unpkg.com/final-form@4.0.3/dist/index.d.ts).
